language: python

python:
  - "3.6"

sudo: false

env:
  - TOX_ENV=py27-django111lts
  - TOX_ENV=py35-django111lts
  - TOX_ENV=py36-django111lts
  - TOX_ENV=py35-django20
  - TOX_ENV=py36-django20
  - TOX_ENV=py36-djangomaster

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=py36-djangomaster

install:
  - pip install tox virtualenv setuptools

script:
  - tox -e $TOX_ENV

after_success:
  - pip install codecov
  - codecov -e TOX_ENV

notifications:
  email: false
